#!/bin/busybox sh

/bin/busybox --install -s

mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp
# fix busybox tty
setsid cttyhack sh
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
sh
