#!/bin/sh

/bin/mount -t devtmpfs devtmpfs /dev
/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys

exec 0</dev/hvc0
exec 1>/dev/hvc0
exec 2>/dev/hvc0

echo "============="
echo "connected to fpga hvc0"
echo "============="
    
while true; do
    /bin/sh
    echo "Shell exited. Restarting..."
    sleep 1
done
