#!/bin/sh

c:/altera/quartus60//bin/perl561/bin/perl -I$sopc_builder/bin -I$sopc_builder/bin/perl_lib -I$sopc_builder/bin/europa $sopc_builder/bin/ptf_update.pl system_0.ptf 

c:/altera/quartus60//bin/perl561/bin/perl -I$sopc_builder/bin -I$sopc_builder/bin/perl_lib -I$sopc_builder/bin/europa $sopc_builder/bin/mk_systembus.pl --sopc_directory=$sopc_builder --sopc_perl=c:/altera/quartus60//bin/perl561 --sopc_lib_path="C:/DE1/DE1_SD_Card_Audio+c:/altera/kits/nios2_60/components+C:/altera/megacore/ddr_ddr2_sdram-v3.3.0/lib/sopc_builder+C:/altera/megacore/pci_compiler-v4.1.0/lib/sopc_builder+C:/altera/megacore/ddr_ddr2_sdram-v3.4.0/lib/sopc_builder+c:/altera/quartus60/sopc_builder/components+c:/altera/kits/nios2_60/components" --target_module_name=system_0 --system_directory=C:/DE1/DE1_SD_Card_Audio --system_name=system_0 --project_name=DE1_SD_Card_Audio.quartus --sopc_quartus_dir= $1
