#!/bin/sh
# devtmpfs does not get automounted for initramfs
/bin/mount -t devtmpfs devtmpfs /dev

# use the /dev/console device node from devtmpfs if possible to not
# confuse glibc's ttyname_r().
# This may fail (E.G. booted with console=), and errors from exec will
# terminate the shell, so use a subshell for the test
if (exec 0</dev/console) 2>/dev/null; then
    exec 0</dev/console
    exec 1>/dev/console
    exec 2>/dev/console
fi

exec /sbin/init "$@"



##!/bin/busybox sh
#
#/bin/busybox --install -s /bin
#
#mount -t devtmpfs none /dev
#mount -t proc none /proc
#mount -t sysfs none /sys
#mount -t tmpfs none /tmp
#
## finx busyboxy tty
#setsid cttyhack sh
#
#echo /sbin/mdev > /proc/sys/kernel/hotplug
#mdev -s
#
#sh
